---
name: build-container

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_call:
    inputs:
      container-image:
        required: true
        type: string
      labels:
        required: true
        type: string
      tags:
        required: true
        type: string

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          labels: ${{ inputs.labels }}
          tags: ${{ inputs.tags }}

  build-willow:
    uses: ./.github/workflows/build-willow.yml
    needs: build-container
    with:
      container-image: ${{ inputs.container-image }}
