---
name: code formatting
on:
  - pull_request
jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        run: |
          git ls-files -z 'main/*.c' 'main/*.h' |
              xargs -0 --no-run-if-empty clang-format-15 --dry-run --Werror
  editorconfig-checker:
    name: editorconfig-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0
        with:
          version: v3.8.0
      - name: editorconfig-check
        run: editorconfig-checker
